//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignTaskPrac
    {
        public int taskPracId { get; set; }
        public int classId { get; set; }
        public string title { get; set; }
        public string Description { get; set; }
        public int grade { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string sub { get; set; }
        public int isAssign { get; set; }
        public int sem { get; set; }
        public int facId { get; set; }
        public string batch { get; set; }
    
        public virtual facultyLogin facultyLogin { get; set; }
    }
}
