//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignFacSub
    {
        public int facSubId { get; set; }
        public int facId { get; set; }
        public string sub { get; set; }
        public int classId { get; set; }
        public int sem { get; set; }
    
        public virtual facultyLogin facultyLogin { get; set; }
    }
}
