//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class facultyLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facultyLogin()
        {
            this.assignFacSubBatches = new HashSet<assignFacSubBatch>();
            this.assignFacSubs = new HashSet<assignFacSub>();
            this.assignTaskPracs = new HashSet<assignTaskPrac>();
            this.assignTasks = new HashSet<assignTask>();
            this.mentorLogins = new HashSet<mentorLogin>();
        }
    
        public int facId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string contactNo { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignFacSubBatch> assignFacSubBatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignFacSub> assignFacSubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignTaskPrac> assignTaskPracs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignTask> assignTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mentorLogin> mentorLogins { get; set; }
    }
}
