//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentEvolutionSystemEntities : DbContext
    {
        public StudentEvolutionSystemEntities()
            : base("name=StudentEvolutionSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assignFacSubBatch> assignFacSubBatches { get; set; }
        public virtual DbSet<assignFacSub> assignFacSubs { get; set; }
        public virtual DbSet<assignTaskPrac> assignTaskPracs { get; set; }
        public virtual DbSet<assignTask> assignTasks { get; set; }
        public virtual DbSet<batchElective> batchElectives { get; set; }
        public virtual DbSet<facultyLogin> facultyLogins { get; set; }
        public virtual DbSet<mentorLogin> mentorLogins { get; set; }
        public virtual DbSet<sa_Login> sa_Login { get; set; }
        public virtual DbSet<semSub> semSubs { get; set; }
        public virtual DbSet<studentBatch> studentBatches { get; set; }
        public virtual DbSet<studentLogin> studentLogins { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
