//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class semSub
    {
        public int semSubId { get; set; }
        public int sem { get; set; }
        public string subject { get; set; }
        public string subCode { get; set; }
        public int isElective { get; set; }
        public int isActive { get; set; }
    }
}
